# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boppable', '0002_auto_20180310_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.AlterField(
            model_name='party',
            name='passcode',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
