# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boppable', '0003_auto_20180310_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrequest',
            name='track',
        ),
        migrations.AddField(
            model_name='trackrequest',
            name='track_id',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
