# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boppable', '0004_auto_20180310_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrequest',
            name='party',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='suggester',
        ),
        migrations.RemoveField(
            model_name='trackvoting',
            name='track',
        ),
        migrations.AddField(
            model_name='trackvoting',
            name='suggester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boppable.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackvoting',
            name='track_id',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrackRequest',
        ),
    ]
