# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boppable', '0005_auto_20180310_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackvoting',
            options={'ordering': ('-votes',)},
        ),
    ]
